spring:
  ai:
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
    minimax:
      api-key: ${MINIMAX_API_KEY}
  jackson:
    parser:
      allow-unquoted-control-chars: true
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 1916657085@qq.com
    #授权码
    password: kycxjcbaloqkfaij
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    password: 1234567
    username: root
    url: jdbc:mysql://localhost:3306/awesome_cs?useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000
server:
  port: 8085


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:mapper/*.xml

sa-token:
  token-name: Authorization
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  token-style: uuid
  # 是否输出操作日志
  is-log: true